cmake: clang: disable warning C4995 for compatibility
C4995: Function that was marked with pragma deprecated.

Enable this would triggers some error when using clang-tidy with PCH.
Did not investigate but confirmed multiple times it was the cause.

---

error: exception handling was enabled in PCH file but is currently disabled [clang-diagnostic-error]
1 error generated.
Error while processing C:\dev\orc\dfir-orc\tests\OrcLibTest\binary_buffer_test.cpp.
Found compiler errors, but -fix-errors was not specified.
Fixes have NOT been applied.

Found compiler error(s).